// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Design Skills documents
 */
interface DesignSkillsDocumentData {
  /**
   * Title field in *Design Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: design_skills.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Skills List field in *Design Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: design_skills.skills_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skills_list: prismic.ContentRelationshipField<"skills_list">;
}

/**
 * Design Skills document from Prismic
 *
 * - **API ID**: `design_skills`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DesignSkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DesignSkillsDocumentData>,
    "design_skills",
    Lang
  >;

/**
 * Item in *Education Entry → Content*
 */
export interface EducationEntryDocumentDataContentItem {
  /**
   * Education field in *Education Entry → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education_entry.content[].education
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  education: prismic.RichTextField;
}

/**
 * Content for Education Entry documents
 */
interface EducationEntryDocumentData {
  /**
   * Title field in *Education Entry*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education_entry.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Education Entry*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: education_entry.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<EducationEntryDocumentDataContentItem>>;
}

/**
 * Education Entry document from Prismic
 *
 * - **API ID**: `education_entry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducationEntryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EducationEntryDocumentData>,
    "education_entry",
    Lang
  >;

/**
 * Item in *Footer → Credits*
 */
export interface FooterDocumentDataCreditsItem {
  /**
   * Credit field in *Footer → Credits*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.credits[].credit
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  credit: prismic.RichTextField;
}

/**
 * Item in *Footer → Quick Links*
 */
export interface FooterDocumentDataQuickLinksItem {
  /**
   * Label field in *Footer → Quick Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Url field in *Footer → Quick Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  logo: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Credits field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.credits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  credits: prismic.GroupField<Simplify<FooterDocumentDataCreditsItem>>;

  /**
   * Quick Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  quick_links: prismic.GroupField<Simplify<FooterDocumentDataQuickLinksItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Hero Introduction documents
 */
interface HeroIntroductionDocumentData {
  /**
   * Hero Introduction field in *Hero Introduction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_introduction.hero_introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_introduction: prismic.RichTextField;
}

/**
 * Hero Introduction document from Prismic
 *
 * - **API ID**: `hero_introduction`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroIntroductionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeroIntroductionDocumentData>,
    "hero_introduction",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = HeroSlice | EducationSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Job → Tech Stack*
 */
export interface JobDocumentDataTechStackItem {
  /**
   * tech field in *Job → Tech Stack*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: job.tech_stack[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"skill">;
}

/**
 * Content for Job documents
 */
interface JobDocumentData {
  /**
   * Title field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Project ID field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.project_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_id: prismic.KeyTextField;

  /**
   * Start Date field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.start_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  start_date: prismic.KeyTextField;

  /**
   * End Date field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  end_date: prismic.KeyTextField;

  /**
   * Position field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Description field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Responsibilities field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.responsibilities
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  responsibilities: prismic.RichTextField;

  /**
   * Duties field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.duties
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  duties: prismic.RichTextField;

  /**
   * Tech Stack field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.tech_stack[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tech_stack: prismic.GroupField<Simplify<JobDocumentDataTechStackItem>>;
}

/**
 * Job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<JobDocumentData>, "job", Lang>;

/**
 * Item in *Header → Navigation*
 */
export interface NavigationDocumentDataNavigationItem {
  /**
   * Label field in *Header → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * url field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Content for Header documents
 */
interface NavigationDocumentData {
  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<
    Simplify<NavigationDocumentDataNavigationItem>
  >;

  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  logo: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * CTA Label field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Other Skills documents
 */
interface OtherSkillsDocumentData {
  /**
   * Title field in *Other Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: other_skills.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Skills List field in *Other Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: other_skills.skills_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skills_list: prismic.ContentRelationshipField<"skills_list">;
}

/**
 * Other Skills document from Prismic
 *
 * - **API ID**: `other_skills`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OtherSkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OtherSkillsDocumentData>,
    "other_skills",
    Lang
  >;

/**
 * Item in *Settings → Open Graph*
 */
export interface SettingsDocumentDataOpenGraphItem {
  /**
   * Title field in *Settings → Open Graph*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Settings → Open Graph*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * url field in *Settings → Open Graph*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * site name field in *Settings → Open Graph*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].site_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * OG Image field in *Settings → Open Graph*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].og_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * locale field in *Settings → Open Graph*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].locale
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  locale: prismic.KeyTextField;

  /**
   * Type field in *Settings → Open Graph*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"website" | "article">;
}

/**
 * Item in *Settings → Twitter X*
 */
export interface SettingsDocumentDataTwitterXItem {
  /**
   * title field in *Settings → Twitter X*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_x[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Settings → Twitter X*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_x[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Twitter X Image field in *Settings → Twitter X*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_x[].twitter_x_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  twitter_x_image: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Open Graph field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.open_graph[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  open_graph: prismic.GroupField<Simplify<SettingsDocumentDataOpenGraphItem>>;

  /**
   * Twitter X field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_x[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  twitter_x: prismic.GroupField<Simplify<SettingsDocumentDataTwitterXItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Skill documents
 */
interface SkillDocumentData {
  /**
   * title field in *Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * icon as name field in *Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.icon_as_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon_as_name: prismic.KeyTextField;

  /**
   * icon field in *Skill*
   *
   * - **Field Type**: Select
   * - **Placeholder**: use Icon as Name if icon not founc
   * - **API ID Path**: skill.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    | "canva"
    | "cloudinary"
    | "contentful"
    | "css"
    | "elementor"
    | "figma"
    | "framer"
    | "github"
    | "html"
    | "javascript"
    | "prismic"
    | "shopify"
    | "typescript"
    | "webflow"
    | "wordpress"
    | "photoshop"
  >;
}

/**
 * Skill document from Prismic
 *
 * - **API ID**: `skill`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillDocumentData>, "skill", Lang>;

/**
 * Content for Skills List documents
 */
interface SkillsListDocumentData {
  /**
   * title field in *Skills List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_list.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * skill field in *Skills List*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: skills_list.skill
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skill: prismic.ContentRelationshipField<"skill">;
}

/**
 * Skills List document from Prismic
 *
 * - **API ID**: `skills_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SkillsListDocumentData>,
    "skills_list",
    Lang
  >;

/**
 * Content for Tech Skills documents
 */
interface TechSkillsDocumentData {
  /**
   * Title field in *Tech Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_skills.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Skills List field in *Tech Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tech_skills.skills_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  skills_list: prismic.ContentRelationshipField<"skills_list">;
}

/**
 * Tech Skills document from Prismic
 *
 * - **API ID**: `tech_skills`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechSkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TechSkillsDocumentData>,
    "tech_skills",
    Lang
  >;

export type AllDocumentTypes =
  | DesignSkillsDocument
  | EducationEntryDocument
  | FooterDocument
  | HeroIntroductionDocument
  | HomePageDocument
  | JobDocument
  | NavigationDocument
  | OtherSkillsDocument
  | SettingsDocument
  | SkillDocument
  | SkillsListDocument
  | TechSkillsDocument;

/**
 * Primary content in *Education → Primary*
 */
export interface EducationSliceDefaultPrimary {
  /**
   * Heading field in *Education → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Section ID field in *Education → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.primary.section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *Education → Items*
 */
export interface EducationSliceDefaultItem {
  /**
   * Education Entry field in *Education → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: education.items[].education_entry
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  education_entry: prismic.ContentRelationshipField<"education_entry">;
}

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EducationSliceDefaultPrimary>,
  Simplify<EducationSliceDefaultItem>
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSlice = prismic.SharedSlice<
  "education",
  EducationSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Introduction field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * CTA Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Default variation for Job Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Job*
 */
type JobSliceVariation = JobSliceDefault;

/**
 * Job Shared Slice
 *
 * - **API ID**: `job`
 * - **Description**: Job
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobSlice = prismic.SharedSlice<"job", JobSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DesignSkillsDocument,
      DesignSkillsDocumentData,
      EducationEntryDocument,
      EducationEntryDocumentData,
      FooterDocument,
      FooterDocumentData,
      HeroIntroductionDocument,
      HeroIntroductionDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      JobDocument,
      JobDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      OtherSkillsDocument,
      OtherSkillsDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SkillDocument,
      SkillDocumentData,
      SkillsListDocument,
      SkillsListDocumentData,
      TechSkillsDocument,
      TechSkillsDocumentData,
      AllDocumentTypes,
      EducationSlice,
      EducationSliceDefaultPrimary,
      EducationSliceDefaultItem,
      EducationSliceVariation,
      EducationSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      JobSlice,
      JobSliceVariation,
      JobSliceDefault,
    };
  }
}
