// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  education: dynamic(() => import("./Education")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  job: dynamic(() => import("./About")),
};
